##!smake

include /usr/include/make/commondefs

TARGETS = smooth
CFILES  = $(TARGETS:=.c) glm.c gltb.c
LLDLIBS = -lglut -lGLU -lGL -lXmu -lXext -lX11 -lm
LCFLAGS = -fullwarn -I$(GLUT) -L$(GLUT)
OPTIMIZER = -O

default		: $(TARGETS)

include $(COMMONRULES)

$(TARGETS)	: $(OBJECTS)
	$(CCF) -o $@ $(OBJECTS) $(LDFLAGS)
